# Generated by Django 3.2 on 2023-01-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230109_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=77),
        ),
    ]
