# Generated by Django 3.2 on 2023-01-09 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='tweet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.tweet'),
            preserve_default=False,
        ),
    ]
